HD <- na.omit(heart_disease_clean)
HD['hdpresence']= ifelse(HD['num']>0,1,0)
HD$hdpresence <-factor(HD$hdpresence)
View(HD)
HD$sex <- factor(HD$sex)
levels(HD$sex)
HD$cp <- factor(HD$cp)
levels(HD$cp)
HD$fbs <- factor(HD$fbs)
levels(HD$fbs)
HD$restecg <- factor(HD$restecg)
levels(HD$restecg)
HD$exang <- factor(HD$exang)
levels(HD$exang)
HD$slope <- factor(HD$slope )
levels(HD$slope)
HD$thal <- factor(HD$thal )
levels(HD$thal)
str(HD)
x <- HD[,c(1:13)]
y <- factor(HD$hdpresence)
levels(y)
c50fit1 <- C5.0(x, y)
summary(c50fit1)
